### ISSUE TITLE
Add an USL generator from IEML structures.

### ISSUE THREAD

**Issue by vletard** [IEMLdev/ieml-reasoner#4]
An USL generator would facilitate the manipulation of results of analogical equations by allowing comparison with other words (or polymorphemes/morphemes), linking to the edition interface of intlekt or more.

**Comment by ogrergo** [comment]
I think maybe adding a "toString()" to: Morpheme, FlexionSet, Polymorpheme, Lexeme, Role, SyntagmaticFunction and Word that return the IEML string.
difficulty:
1) the morpheme, and composing USL have to be written in the IEML order, do we use the API to render the usl or do we implement the feature ?

**Comment by vletard** [comment]
The issue with `toString()` is that it makes no difference between units that _can_ produce USLs and units that _cannot_. I would rather go with a `toUSL()` method in some interface that Word, Polymorpheme and Morpheme would implement but not the others.

As for rewriting the generator, I would go for yes. I think it would be beneficial for detecting issues in the generation process and also be a potential basis for porting the python library.

**Comment by ogrergo** [comment]
There is just a point that bother me : in that library, the name "USL" will refer to : 
 - the string representation of an IEML object
 - maybe the name of the super class of all IEML Object

If that the case, maybe calling it, toUSLString() ?
In the python lib, I also used this function as the __hash__ method of USL python objects (in addition to the __str__ magic method)

**Comment by vletard** [comment]
No problem with naming the method `toUSLString()`.

In my understanding, the USL is the character string encoding an IEML object. However, not all of them have an USL representation, that's why the super class is not called USL, but IEMLUnit.
Let me know if I got something wrong.
